CREATE TABLE IF NOT EXISTS booking_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    kind VARCHAR(255) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    UNIQUE (booking_id, kind)
);
CREATE INDEX IF NOT EXISTS booking_emails_due_idx ON booking_emails(next_attempt_at) WHERE sent_at IS NULL;
-- Only the trusted backend DB connection accesses recipients and email content.
ALTER TABLE booking_emails ENABLE ROW LEVEL SECURITY;
