ALTER TABLE bookings ADD COLUMN IF NOT EXISTS service_price_snapshot NUMERIC(15,0);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS revenue_estimated BOOLEAN NOT NULL DEFAULT FALSE;
-- No existing booking data is rewritten. Legacy estimates are calculated when reading reports.
CREATE INDEX IF NOT EXISTS bookings_revenue_idx ON bookings(salon_id, completed_at) WHERE status = 'COMPLETED';
CREATE TABLE IF NOT EXISTS platform_fee_policies (
    effective_month DATE PRIMARY KEY,
    percent NUMERIC(5,2) NOT NULL CHECK (percent >= 0 AND percent <= 100)
);
CREATE TABLE IF NOT EXISTS platform_billing_settings (id BIGINT PRIMARY KEY, qr_url VARCHAR(255));
INSERT INTO platform_billing_settings(id) VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS platform_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id),
    billing_month DATE NOT NULL,
    paid_amount NUMERIC(15,0) NOT NULL DEFAULT 0,
    paid_at TIMESTAMP, confirmed_by UUID, reminded_at TIMESTAMP,
    UNIQUE(salon_id,billing_month)
);
ALTER TABLE booking_emails ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE platform_fee_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_billing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_statements ENABLE ROW LEVEL SECURITY;
