-- Run once in Supabase SQL Editor before starting the new backend (ddl-auto: none).
BEGIN;
CREATE TABLE IF NOT EXISTS public.salon_profile_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES public.salons(id),
    proposed JSONB NOT NULL,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('PROFILE', 'COVER', 'GALLERY')),
    previous_logo_url TEXT,
    proposed_logo_url TEXT,
    previous_image_urls JSONB,
    proposed_image_urls JSONB,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    submitted_at TIMESTAMPTZ NOT NULL,
    reviewed_at TIMESTAMPTZ,
    reviewed_by UUID
);
CREATE INDEX IF NOT EXISTS idx_salon_profile_changes_status ON public.salon_profile_changes(status, id);
CREATE INDEX IF NOT EXISTS idx_salon_profile_changes_salon ON public.salon_profile_changes(salon_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_salon_profile_changes_pending ON public.salon_profile_changes(salon_id) WHERE status = 'PENDING';
ALTER TABLE public.salon_profile_changes ENABLE ROW LEVEL SECURITY;
-- Access goes through the backend's database role, never directly through the public API.
COMMIT;
