server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: booking-nail-ms

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  cache:
    type: simple

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    com.bookingnailms: DEBUG
    org.springframework.security: INFO

app:
  cognito:
    issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_iUMERg77o
    client-id: 10ivodmqmsklu4gqkqj1qcgr0h

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
